<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Authentification</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0bfe37d9-e5df-4777-96ca-57b63c461e08</testSuiteGuid>
   <testCaseLink>
      <guid>549dc45f-2a1b-4e12-b6ee-697258cd112d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentification/TC00_AuthentificationAvecPwdVide</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb84ff67-fda5-4484-aa44-7cbe840ac580</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64e92300-9c74-47dd-9ecf-c8c92440f590</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1dc8583-238c-4c7f-a3a0-8c3e04705ba1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentification/TC01_AuthentificationAvecPwdInvalide</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd373012-e7ea-46ea-a6ed-92f0000d8dc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b656c09-3bd9-4378-8314-7002abf2bb61</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>733e04d7-d2d9-4554-a777-345103c30dd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentification/TC02_AuthentificationAvecIdentifiantVide</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62e12d5e-0c0c-48ab-be89-005d859226ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>faf87b27-35df-4f7f-b75f-83593b3d7d44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42f3e322-c20c-4bde-b699-521928dcd904</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentification/TC03_AuthentificationAvecIdentifiantInvalide</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98f0b2c0-976e-4ea6-b667-294245cb589f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07ebffc8-cc86-4064-9928-894e7bd3d2eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dab3bd3f-380a-446f-9ad4-6a47e0402698</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentification/TC04_AuthentificationAvecIdentifiantPwdInvalide</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e15a5e81-25e5-4251-85a9-a7d70c3d7e4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f528e79-90fb-4aa5-8ad5-b68968d31346</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a74b63b-6718-4c21-b7d3-3d90f16d5aa2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentification/TC05_AuthentificationAvecIdentifiantPwdVide</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b0db133-a66e-4d42-aa93-f71af597583e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99788779-201a-40f4-8ca6-a4955794f068</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f414bf12-5538-4db8-b4a6-cd509fb5f20d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentification/TC06_AuthentificationValide</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c70c53a2-1c67-482d-b9df-49fe5c1a4415</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd309868-c2ed-41cf-980b-6b68169f8002</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00765e1a-ebce-4fc3-9588-6568501424d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentification/TC07_SeDeconnecter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
